apiVersion: v1
kind: Service
metadata:
  name: user-api-sql-service-srv
spec:
  type: NodePort
  selector:
    app: user-api-sql-service
  ports:
    - name: user-api-sql-service
      protocol: TCP
      port: 80
      targetPort: 80